stages:
  - test

test-p37:
  image: python:3.7
  stage: test
  script:
    - pip install .
    - pip install -r requirements-dev.txt
    - flake8 --max-line-length 120
    - pytest --cov .

test-p36:
  image: python:3.6
  stage: test
  script:
    - pip install .
    - pip install -r requirements-dev.txt
    - flake8 --max-line-length 120
    - pytest --cov .
