name: Code Coverage

on:
  [push, pull_request]

jobs:
  run:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-cov
        pip install numpy==1.26.4
        pip install .
        pip install odfpy     # optional dependencies
        pip install openpyxl  # idem
        pip install xlrd      # idem
    - name: Generate coverage report
      run: |
        pytest --cov ./moonstone --cov-report xml --cov-report term
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
